name: automated-deployment
on: [pull_request]
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
jobs:
  build:
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to Azure
        uses: azure/login@v1
        with:  
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Build and deploy frontend Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/recipe-demo
          acrName: reactrecipeapp
          containerAppName: react-app-recipe
          resourceGroup: RecipeWebsite
      
      - name: Build and deploy backend Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/recipe-backend
          acrName: RecipeBackend
          containerAppName: react-app-recipe-backend
          resourceGroup: RecipeWebsite
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
