name: automated-Deployment
run-name: ${{ github.actor }} made a pull request, starting automatic test
on: [pull_request]
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
jobs: 
  autodeploy:
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - name: Log into Azure
        uses: azure/login@v1
        with:
          enable-oidc: true
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
