name: automatic-test
run-name: ${{ github.actor }} made a pull request, starting automatic test
on: [pull_request]
jobs:
  automatic-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
         ref: main
      - name: Change Working Directory
        run: cd ./recipe-demo
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npm run test
